### ISSUE TITLE
node 10 can not start

### ISSUE THREAD

**Issue by parsibox** [wddqing/node-http-proxy#1]
```
server start error TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received type function
at normalizeSpawnArguments (child_process.js:413:11)
    at Object.exports.spawn (child_process.js:515:38)
    at Command.<anonymous> (/usr/lib/node_modules/node-http-proxy/bin/node-http-proxy:62:28)
    at Command.listener (/usr/lib/node_modules/node-http-proxy/node_modules/commander/index.js:287:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/lib/node_modules/node-http-proxy/node_modules/commander/index.js:541:12)
    at Command.parse (/usr/lib/node_modules/node-http-proxy/node_modules/commander/index.js:427:21)
    at Object.<anonymous> (/usr/lib/node_modules/node-http-proxy/bin/node-http-proxy:94:9)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)

```

**Comment by cjahv** [comment]
me too. use node 8
```shell
server start error TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:403:11)
    at Object.exports.spawn (child_process.js:496:38)
    at Command.<anonymous> (/Users/jahv/.config/yarn/global/node_modules/node-http-proxy/bin/node-http-proxy:62:28)
    at Command.listener (/Users/jahv/.config/yarn/global/node_modules/commander/index.js:287:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/Users/jahv/.config/yarn/global/node_modules/commander/index.js:541:12)
    at Command.parse (/Users/jahv/.config/yarn/global/node_modules/commander/index.js:427:21)
    at Object.<anonymous> (/Users/jahv/.config/yarn/global/node_modules/node-http-proxy/bin/node-http-proxy:94:9)
    at Module._compile (module.js:652:30)
```

**Comment by shaoran** [comment]
me too, node v10.15.1

```
$ node_modules/.bin/nproxy start -p 3128 -i 1
server start error TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received type function
    at normalizeSpawnArguments (child_process.js:422:11)
    at Object.spawn (child_process.js:532:38)
    at Command.<anonymous> (/home/yanez/tmp/p/node_modules/node-http-proxy/bin/node-http-proxy:62:28)
    at Command.listener (/home/yanez/tmp/p/node_modules/commander/index.js:287:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (/home/yanez/tmp/p/node_modules/commander/index.js:541:12)
    at Command.parse (/home/yanez/tmp/p/node_modules/commander/index.js:427:21)
    at Object.<anonymous> (/home/yanez/tmp/p/node_modules/node-http-proxy/bin/node-http-proxy:94:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by wddqing** [comment]
v0.2.4 fix the issue
